### PR TITLE
Biomancy mod compat fix 1.20.1+

### PR DESCRIPTION
**Pull request by Igneaalis**
Fixes conflict with this Biomancy mixin:
```java
@WrapWithCondition(method = "applySplash", at = @at(value = "INVOKE", target = "Lnet/minecraft/world/entity/LivingEntity;addEffect(Lnet/minecraft/world/effect/MobEffectInstance;Lnet/minecraft/world/entity/Entity;)Z"))
```
[Source](https://github.com/Elenterius/Biomancy/blob/mc1.20.1/prod/src/main/java/com/github/elenterius/biomancy/mixin/ThrownPotionMixin.java)

Special thanks to: @llamalad7 from SpongePowered Discord server

### CODE REVIEW

**Comment by Igneaalis** [comment]
It's also works for FeudalKings branch

**Comment by KingKottlewing** [comment]
Is this the fix for this issue? If so, how can I implement it on my server? Thanks

[https://mclo.gs/zR8xgrZ](url)
Screenshot 2024-07-27 at 14 45 51
Screenshot 2024-07-27 at 14 46 05
Screenshot 2024-07-27 at 14 46 17

**Comment by Igneaalis** [comment]
> Is this the fix for this issue? If so, how can I implement it on my server? Thanks
> 
> [https://mclo.gs/zR8xgrZ](url) Screenshot 2024-07-27 at 14 45 51 Screenshot 2024-07-27 at 14 46 05 Screenshot 2024-07-27 at 14 46 17

Yes, it's the fix for this problem. Just copy my changes and compile Arclight

**Comment by Igneaalis** [comment]
https://github.com/IzzelAliz/Arclight/pull/1421/commits/3dbde0e0024b79676aa3df572cd77ed0ae4f745a

**Pull request closed without merging**
