### PR TITLE
Issues Form & Remove issue bot

### PR DESCRIPTION
**Pull request by ahdg6**
It's clear that your issuebot is blocking user from reporting issues.
I know it's important to make user provide full details but there is another way --- Make it easier for people to use.

In this PR, I introduce two issue form for you and it should look like this
图片

Simple and elegant, issuebot will not be needed any more, cheer!

### CODE REVIEW

**Comment by timi137137** [comment]
No, do not accept this pr. A user who asks a question should have basic network quality

**Comment by ahdg6** [comment]
why not? a issue form will solve these problems. User must type info in right format

**Comment by timi137137** [comment]
I know, and your form format will be included, but bot cannot be removed

**Comment by ahdg6** [comment]
I'm adding issuebot back, just reopen the PR then it will be sync.

Note: Issuebot don't allow ### in my test. Please ensure your issuebot will not affect form if you are going to merge it.

**Comment by timi137137** [comment]
so i close this ,because i need update bot

**Comment by ahdg6** [comment]
ok. I get it. Good Luck to you.

**Comment by timi137137** [comment]
you too

**Pull request closed without merging**
