### PR TITLE
fix mod sign error

### PR DESCRIPTION
**Pull request by sj-hub9796**
may fixed:
- https://github.com/IzzelAliz/Arclight/issues/1502
- https://github.com/IzzelAliz/Arclight/issues/1394
- https://github.com/IzzelAliz/Arclight/issues/1135

of course i am pretty noob of mixin.
is there better idea than this?

### CODE REVIEW

**Comment by qyl27** [comment]
Thanks a lot.

**Comment by AdriianFdz** [comment]
Hi, the SecurityCraft mod signs are getting broken at the same way. Could you make a hotfix of that? Thanks!

image

**Comment by sj-hub9796** [comment]
> Hi, the SecurityCraft mod signs are getting broken at the same way. Could you make a hotfix of that? Thanks!

r u sure you did update to new version?
try delete ``.arclight`` directory and launch the server again

**Comment by AdriianFdz** [comment]
Tryed deleting .arclight but still the same bug. Im using arclight-forge-1.20.1-1.0.6-SNAPSHOT

The vanilla signs are working perfectly

**Comment by sj-hub9796** [comment]
> Tryed deleting .arclight but still the same bug. Im using arclight-forge-1.20.1-1.0.6-SNAPSHOT
> 
> The vanilla signs are working perfectly

https://github.com/IzzelAliz/Arclight/actions/runs/12326781537/artifacts/2320483745

u need to try this version.
delete ``.arclight`` directory and try again

thx

**Comment by AdriianFdz** [comment]
I´ve tryed that version.
However, I reinstalled and installed that version again, deleting .arclight. Same bug. 
The security craft sign seems to be placed, but the error continues appearing in console.
No errors when are vanilla signs.
Thanks for the fast responses :)

**Comment by sj-hub9796** [comment]
> I´ve tryed that version. However, I reinstalled and installed that version again, deleting .arclight. Same bug. The security craft sign seems to be placed, but the error continues appearing in console. No errors when are vanilla signs. Thanks for the fast responses :)

hmm, can you try other mods sign?

**Comment by AdriianFdz** [comment]
Hi again,

Farmers Delight signs (hanging) are throwing the same exception. The mod doesnt have "normal" signs

**Comment by sj-hub9796** [comment]
> Hi again,
> 
> Farmers Delight signs (hanging) are throwing the same exception. The mod doesnt have "normal" signs

https://github.com/user-attachments/assets/2040f948-4631-4f23-82b0-faf148d3b919


well, works fine for me

**Comment by AdriianFdz** [comment]
well, and no errors in console? I can place them too, but console get spammed with that error. Not sure why...

**Comment by sj-hub9796** [comment]
> I´ve tryed that version. However, I reinstalled and installed that version again, deleting .arclight. Same bug. The security craft sign seems to be placed, but the error continues appearing in console. No errors when are vanilla signs. Thanks for the fast responses :)

well, if you have protocollib or ItemsAdder like something in your plugins, that's normal

**Comment by AdriianFdz** [comment]
Ye, I have protocolib. Any fix? or just removing that plugin

**Comment by sj-hub9796** [comment]
> Ye, I have protocolib. Any fix? or just removing that plugin

i mean, you can't place that sign?
or sign gui doesn't appear

**Comment by AdriianFdz** [comment]
I can place it and it seems to work everything, but im afraid that the console error makes my server crash cause it drops the exception everytime I place each sign

**Comment by sj-hub9796** [comment]
> I can place it and it seems to work everything, but im afraid that the console error makes my server crash cause it drops the exception everytime I place each sign

no, it won't crash. that's fine.
what is your protocollib version?
try /version ProtocolLib

**Comment by AdriianFdz** [comment]
Good. 
ProtocolLib version 5.3.0

**Comment by sj-hub9796** [comment]
> Reference

hmm, try downgrade if you can.

**Comment by AdriianFdz** [comment]
I get crashes at login when I downgrade version. Seems that FastLogin requires 5.3.0 version, cause 5.2.0 don´t allow me to login into the server. IDK if you have any specific version to try.

**Comment by sj-hub9796** [comment]
> I get crashes at login when I downgrade version. Seems that FastLogin requires 5.3.0 version, cause 5.2.0 don´t allow me to login into the server. IDK if you have any specific version to try.

um, then just use 5.3.0.
and if the exception bother you, try this plugin: https://www.spigotmc.org/resources/console-spam-fix.18410/
also can you send me full logs?

**Comment by AdriianFdz** [comment]
All right, thanks. 
Here you have the logs. Exception shows at [23Dec2024 12:23:40.421]

[2024-12-23-2.log](https://github.com/user-attachments/files/18240566/2024-12-23-2.log)

**Comment by sj-hub9796** [comment]
> All right, thanks. Here you have the logs. Exception shows at [23Dec2024 12:23:40.421]
> 
> [2024-12-23-2.log](https://github.com/user-attachments/files/18240566/2024-12-23-2.log)

oof, sry for late.
it wasn't Protocollib issue. it was CoreProtect.

**Comment by AdriianFdz** [comment]
Oh no problem, these are tricky dates.

All right, so if anyone knows any way to fix it apart from hiding them through external plugin, would be great ^^

**Pull request merged**
